# Generated by Django 3.1.7 on 2021-03-03 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
